name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: >-
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=Release
          -DXET_CDC_WARNINGS_AS_ERRORS=ON

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build --output-on-failure

